services:
    php-fpm:
        build:
            context: ./.docker/php-fpm/
        container_name: ich-dvo-ru-php-fpm
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - ich-dvo-ru
        depends_on:
            - mariadb

    mariadb:
        image: "mariadb:11"
        container_name: ich-dvo-ru-mariadb
        restart: unless-stopped
        ports:
            - "${DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - "ich-dvo-ru-mariadb:/var/lib/mysql"
        networks:
            - ich-dvo-ru
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - "--connect"
                - "--innodb_initialized"
            retries: 3
            timeout: 5s

    nginx:
        image: nginx:1.21.6
        container_name: ich-dvo-ru-nginx
        restart: unless-stopped
        labels:
            traefik.enable: true
            traefik.http.routers.nginx.rule: "Host(`${APP_HOST}`)"
        volumes:
            - ./.docker/nginx/ich.dvo.ru.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
        networks:
            - ich-dvo-ru
        depends_on:
            - php-fpm

    traefik:
        image: traefik:v3.1.2
        container_name: ich-dvo-ru-traefik
        restart: unless-stopped
        command:
            - --api.insecure=true
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entryPoints.web.address=:80"
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - ich-dvo-ru
        depends_on:
            - nginx

    bun:
        image: oven/bun:1.1
        container_name: ich-dvo-ru-bun
        working_dir: /var/www/
        profiles:
            - donotstart
        ports:
            - 5173:5173
        volumes:
            - ./:/var/www
        networks:
            - ich-dvo-ru

networks:
    ich-dvo-ru:
        driver: bridge

volumes:
    ich-dvo-ru-mariadb:
        driver: local
