version: "3"

tasks:
  build:
    desc: "Собрать проект с нуля. Выполнять после клонирования репозитория"
    cmds:
      - '{{if eq OS "windows"}}powershell{{end}} cp ./.env.example ./.env'
      - docker compose build
      - task: up-d
      - task: exec
        vars: { CLI_ARGS: "git config --global --add safe.directory /var/www" }
      - task: composer
        vars: { CLI_ARGS: "install" }
      - task: bun
        vars: { CLI_ARGS: "install" }
      - task: artisan
        vars: { CLI_ARGS: "storage:link" }
      - task: artisan
        vars: { CLI_ARGS: "key:generate" }
      - task: migrate

  deploy:
    desc: "Выполнить операции, нужные для развёртывания на рабочем окружении"
    cmds:
      - task: build
      - task: bun
        vars: { CLI_ARGS: "run build" }
      - task: artisan
        vars: { CLI_ARGS: "optimize" }

  up:
    desc: "Создать и запустить контейнеры"
    cmds:
      - docker compose up {{.CLI_ARGS}}

  up-d:
    desc: "Создать и запустить контейнеры на фоне"
    cmds:
      - docker compose up -d {{.CLI_ARGS}}

  down:
    desc: "Остановить и удалить контейнеры"
    cmds:
      - docker compose down {{.CLI_ARGS}}

  start:
    desc: "Запустить контейнеры"
    cmds:
      - docker compose start {{.CLI_ARGS}}

  stop:
    desc: "Остановить контейнеры"
    cmds:
      - docker compose stop {{.CLI_ARGS}}

  migrate:
    desc: "Выполнить миграции базы данных"
    cmds:
      - task: artisan
        vars: { CLI_ARGS: "migrate {{.CLI_ARGS}}" }

  seed:
    desc: "Наполнить базу тестовыми данными"
    cmds:
      - task: artisan
        vars: { CLI_ARGS: "db:seed {{.CLI_ARGS}}" }

  vite:
    desc: "Запустить Vite Developer Server"
    cmds:
      - task: bun
        vars: { CLI_ARGS: "run dev --host {{.CLI_ARGS}}" }

  artisan:
    desc: "Запуск команд Laravel Artisan из контейнера"
    cmds:
      - task: php
        vars: { CLI_ARGS: "artisan {{.CLI_ARGS}}" }

  php:
    desc: "Запуск команд PHP из контейнера"
    cmds:
      - task: exec
        vars: { CLI_ARGS: "php {{.CLI_ARGS}}" }

  composer:
    desc: "Запуск команд Composer из контейнера"
    cmds:
      - task: exec
        vars: { CLI_ARGS: "composer {{.CLI_ARGS}}" }

  exec:
    desc: "Запуск команд контейнера 'php-fpm'"
    cmds:
      - docker compose exec php-fpm {{.CLI_ARGS}}

  bun:
    desc: "Одноразовый запуск контейнера 'bun' для выполнения команд Bun"
    cmds:
      - docker compose run --rm --service-ports bun bun {{.CLI_ARGS}}
